version: '3.8'

services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env # Load environment variables from the .env file
    depends_on:
      - adminer

  postgres:
    image: postgres:13.1
    container_name: nestjs-database-connection-postgres-db
    restart: always
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: nestjs-db
    volumes:
      - nestjs_postgres_db:/data/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: nestjs-database-connection-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: ep-restless-rice-a5ilnoib-pooler.us-east-2.aws.neon.tech
    ports:
      - 8080:8080

volumes:
  nestjs_postgres_db:
